# Generated by Django 4.2.4 on 2023-10-11 21:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_applications_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='applications',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications_customer_set', to='project.users'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='moderator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.users'),
        ),
        migrations.AlterField(
            model_name='applicationsoptions',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.applications'),
        ),
        migrations.AlterField(
            model_name='applicationsoptions',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.options'),
        ),
    ]
