# Generated by Django 4.2.4 on 2023-10-11 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_applications_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationsoptions',
            name='amount',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
