# Generated by Django 4.2.4 on 2023-10-21 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_remove_options_image_options_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='options',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
