# Generated by Django 4.2.4 on 2023-10-23 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_alter_options_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='options',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
