# Generated by Django 4.2.4 on 2023-11-15 14:12

from django.db import migrations
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_alter_options_description'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='users',
            managers=[
                ('objects', project.models.NewUserManager()),
            ],
        ),
    ]
