# Generated by Django 4.2.4 on 2023-11-15 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_alter_users_managers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='login',
            new_name='email',
        ),
    ]
